name: E-Commerce CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/ECommerce-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "ECommerce-0.0.1-SNAPSHOT.jar"
          target: "/home/${{ secrets.AWS_USERNAME }}/ecommerce"

      - name: Restart server with systemd
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/${{ secrets.AWS_USERNAME }}/ecommerce
            mv -f ECommerce-0.0.1-SNAPSHOT.jar ecommerce.jar
            sudo chown ${{ secrets.AWS_USERNAME }}:${{ secrets.AWS_USERNAME }} ecommerce.jar
            sudo chmod +x ecommerce.jar
            sudo systemctl restart ecommerce.service
