name: E-Commerce CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/ECommerce-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "ECommerce-0.0.1-SNAPSHOT.jar"
          target: "/home/${{ secrets.AWS_USERNAME }}/app"

      - name: Restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/${{ secrets.AWS_USERNAME }}/app
            
            # Find and kill the old process. The '|| true' ensures this step never fails.
            pkill -f "ecommerce.jar" || true
            sleep 5 # Give a moment for the port to be released
            
            mv -f ECommerce-0.0.1-SNAPSHOT.jar ecommerce.jar
            
            nohup env \
              SPRING_DATASOURCE_URL=jdbc:mysql://${{ secrets.DB_HOST }}:3306/${{ secrets.DB_NAME }}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC \
              SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }} \
              SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }} \
              JWT_SECRET=${{ secrets.JWT_SECRET }} \
              SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect \
              java -jar -Dspring.profiles.active=prod --server.port=8081 ecommerce.jar > /dev/null 2>&1 &

            exit 0 # Explicitly exit with a success code to prevent action failure
